### PR TITLE
C22: SSH and remote access (+C10 video addition)

### PR DESCRIPTION
**Pull request by essihe**
added video intro, reading material and link to aalto scicomp

### CODE REVIEW

**Comment by essihe** [comment]
I added a short video on ssh by sw carpentry and Aalto column link pointing to aalto scicomp ssh page. For reading I found this: https://www.ssh.com/ssh/command but please tell me if you have any suggestions, or something better in mind for this section (I have limited knowledge of this area but evaluated these sources as must-know basic info to get started)

**Comment by rkdarst** [comment]
The ssh.com link is a private company (actually a Finnish julkinen osakeyhtiö - ssh was created here!) which I think has a slightly different product than the usual OpenSSH, though the options seem identical so I wonder if the situation has changed.  Though it's hard to find something better, and it's kind of late.  I'll think about it tomorrow.

**Comment by essihe** [comment]
https://www.startutorial.com/articles/view/ssh-basics-part-1-introduction this was my second option for reading material but as I said, I only gathered material that made any sense to me so probably these are not the best sources

**Comment by essihe** [comment]
https://www.mn.uio.no/geo/english/services/it/help/using-linux/ssh-tips-and-tricks.html   this page seems to gather quite a lot of information starting from the basics.

**Pull request merged**
