### PR TITLE
B21 Jupyter Notebooks

### PR DESCRIPTION
**Pull request by essihe**
- jupyter notebook introduction and installation verification added

### CODE REVIEW

**Comment by essihe** [comment]
Please see if structure ok and suggest your ideas for what is essential to include.

**Comment by rkdarst** [comment]
Looks good to me!  I think this is a pretty good model of text for a lesson that motivates people some (I hadn't thought of this before...).

Want do add a video in with it an the same time? (in `courses/B.yaml`).  You said you had found some good ones...

**Comment by rkdarst** [comment]
I'll just merge, it's better and we can go from here... thanks!

**Comment by rkdarst** [comment]
Oh, you said WIP here.  Well, I'll leave it, but it looks good.

**Pull request merged**
