### PR TITLE
Add figure, description of relationship between the levels

### PR DESCRIPTION
**Pull request by rkdarst**
Here I've described our new levels and added a figure showing their dependencies.

Critical feedback requested, since this is how we frame everything that comes after.  Please discuss well.

### CODE REVIEW

**Comment by bast** [comment]
Rendered figure: https://github.com/coderefinery/handsonscicomp/blob/figure/source/levels.svg

**Comment by bast** [comment]
F: copy paste error in text

**Comment by bast** [comment]
Today while walking to work I was thinking about this figure without seeing this PR and also thought of two tracks: one is "consuming" programs written by others, the other is writing programs.

**Comment by bast** [comment]
How will A and B differentiate?

**Comment by rkdarst** [comment]
The "consuming what others have written" vs "writing your own" is a
good distinction.  It seems that only E and F are truly about making
your own stuff, though (perhaps some of B, too?)  If you can organize
it well let me know.

As for A vs B.  I wanted a "level zero" that was basically a "basic
staff intro":
- who to ask for help
- what resources are available and when you'd use them
The "setting up your computer" went in there too but maybe should be
somewhere else.  So it should be feasible to have *everyone* know
A01.  What do you think?

**Comment by bast** [comment]
> The "consuming what others have written" vs "writing your own" is a good distinction. It seems that only E and F are truly about making your own stuff, though (perhaps some of B, too?) If you can organize it well let me know. 

I was thinking that it would branch - I think your suggestion is good.

**Comment by bast** [comment]
> As for A vs B. I wanted a "level zero" that was basically a "basic staff intro": - who to ask for help - what resources are available and when you'd use them The "setting up your computer" went in there too but maybe should be somewhere else. So it should be feasible to have *everyone* know A01. What do you think?

What will be in B that is not A?

**Comment by rkdarst** [comment]
B would be these "making figures", "making posters", "LaTeX" type of things which we want people to know but aren't direct dependencies of computing.  I will try to have almost nothing in A (I thought about making A a separate 0 level, but then identifiers get less uniform to handle).

**Comment by rkdarst** [comment]
I realized that the important path wasn't clear in the figure, so I made this version which de-emphasizes the B level away from the main pathway:
levels2

I think we could throw B onto the right side instead of the left, that may look more natural (even if B and C are out of order then).

This doesn't have the division between producing code and using code, but if B was above E it could almost be divided by colors into the top left (using) and bottom right (producing)

**Comment by bast** [comment]
I like the figure now. I would keep B on the left as it is.

**Comment by rkdarst** [comment]
Updated the figure and the text a bit.  It's not perfect, but I think it's good enough to frame the problem for now and we can improve later once there is more discussion.  What do you think?

**Comment by rkdarst** [comment]
A combination of conflicting upstream changes when I tried to rearrange the course data, docutils 0.15 breaking sphinx, and error messages in the substituntion extension caused me to decide to merge this.  It seemed like it was approved enough for now - if there are more changes anyone would like, we can still do them.

**Comment by bast** [comment]
I agree - it's a very good start.

**Pull request merged**
