### PR TITLE
B21: Jupyter Notebooks

### PR DESCRIPTION
**Pull request by essihe**
- added new video link for jupyter

### CODE REVIEW

**Comment by essihe** [comment]
By the way; I'm not able to build the project locally anymore.. I get: "Extension error:
Could not import extension course_table (exception: No module named 'sphinx_ext_substitution')"

Nothing should have changed on my end

**Comment by essihe** [comment]
And here's another option for tutorial series but I felt it wasn't as good: https://www.youtube.com/watch?v=9cVYhm12_6o&list=PL_iP0SGUzx9SR_33wUp58T1B-lzO8qNrq

This I thought of too: https://www.youtube.com/watch?v=8O_COC9xtJw  
but it it pretty lengthy, I listened 40mins and don't know if the rest of it is equally good as the beginning

**Comment by rkdarst** [comment]
>  Could not import extension course_table (exception: No module named 'sphinx_ext_substitution')"

Hm, I guess it can't find the Python module `sphinx_ext_substitution`.  Are you in a different virtual environment/conda environment?  Do you have the things from requirements.txt installed? (though, that module is probably the only one that might be missing)

**Comment by rkdarst** [comment]
I really like these playlists which have lots of small things.  But, do you think we could find videos that show JupyterLab instead? Or, is it even time to primarily focus on JupyterLab?

**Comment by essihe** [comment]
> > Could not import extension course_table (exception: No module named 'sphinx_ext_substitution')"
> 
> Hm, I guess it can't find the Python module `sphinx_ext_substitution`. Are you in a different virtual environment/conda environment? Do you have the things from requirements.txt installed? (though, that module is probably the only one that might be missing)

Ok, I figured it out and installed again.. I only wonder why it was suddenly missing..

**Comment by essihe** [comment]
> I really like these playlists which have lots of small things. But, do you think we could find videos that show JupyterLab instead? Or, is it even time to primarily focus on JupyterLab?

I had that in mind too but couldn't find any decent playlist series. I can look for that a bit still

**Comment by essihe** [comment]
> > I really like these playlists which have lots of small things. But, do you think we could find videos that show JupyterLab instead? Or, is it even time to primarily focus on JupyterLab?
> 
> I had that in mind too but couldn't find any decent playlist series. I can look for that a bit still

Seems that the selection for Jupyter Lab tutorials focusing on Jupyter Lab for data analysis is quite narrow..  Mostly tutorials explaining just how to navigate there and not really showing how it can be used for data science.

**Comment by bast** [comment]
This is conflicting. Should I look into this?

**Pull request merged**
